version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - APP_ENV=development
      - MONGO_URI=mongodb://campusfit_user:campusfit_password@mongodb:27017/campusfit_db?authSource=admin
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=campusfit_user
      - MONGO_INITDB_ROOT_PASSWORD=campusfit_password
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: