apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: campusfit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: campusfit
  template:
    metadata:
      labels:
        app: campusfit
    spec:
      containers:
        - name: campusfit
          image: shwetaravnak05/campusfit:v1
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: PORT
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: APP_ENV
            - name: MONGO_URI
              value: "mongodb://admin:campusfit123@mongodb-service:27017/campusfit?authSource=admin"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
